### ISSUE TITLE
Missing getExpirationMonth() and getExpirationYear() in PaymentMethodNonceDetails

### ISSUE THREAD

**Issue by jmsjr** [braintree/braintree_java#117]
### General information

* SDK/Library version: 3.16.1 up to 3.18.0
* Environment: Both
* Language, language version, and OS: Java 1.8.0_322 on Windows10 and Ubuntu 22.04.01 LTS

### Issue description

The on-line documentation indicates a way to obtain the expiration month and expiration year from a nonce:

https://developer.paypal.com/braintree/docs/reference/response/payment-method-nonce#details.expiration_month

However, the methods `getExpirationMonth()` and `getExpirationYear()` are not available in the actual library. I need a way to extract this info from a nonce on the Java-side/server-side.

![image](https://user-images.githubusercontent.com/28499925/192906336-d5ffc8b2-8f4c-4593-858c-d30702ff718c.png)

**Comment by hollabaq86** [comment]
👋 @jmsjr thanks for reaching out and reporting this discrepancy. We'll get this fixed up.

For internal tracking, issue 506

**Comment by saralvasquez** [comment]
Changes to address this have been merged and will be released in the next version of the SDK. Thanks for bringing this to us!
