### ISSUE TITLE
Not found exception does not contain message

### ISSUE THREAD

**Issue by garagatyi** [braintree/braintree_java#18]
I tried create subscription but got NotFoundException without exception message.

I found that java client doesn't use response message from Braintree server to clarify exception cause.
https://github.com/braintree/braintree_java/blob/master/src/main/java/com/braintreegateway/util/Http.java#L82

By the way it seems that server doesn't send such message.

**Comment by jdlc** [comment]
@garagatyi Thanks for pointing this out. We're going to discuss adding this to a future major release of the library. We can't release it now because of the effect on existing integrations, so I'm closing this issue.
