### ISSUE TITLE
Server responds 404 if empty string used as merchant_id, public and private keys

### ISSUE THREAD

**Issue by garagatyi** [braintree/braintree_java#19]
It is more about server behavior than java client.

I've had misconfiguration. Merchant id, public, private keys was set as empty strings.
I tried add credit card to user, add subscriptions and server responded 404.

It would be better to respond 400 Bad request with meaningful error message.

**Comment by jdlc** [comment]
Hi @garagatyi,
​
Thanks for your feedback and I'm sorry it took us so long to respond. This is a good idea and we've explored implementations to solve this across our client libraries for a possible future release. We will provide any updates in this thread. Thanks again!

**Comment by danakatz** [comment]
Starting in [2.69.0](https://github.com/braintree/braintree_java/blob/master/CHANGELOG.md#2690), released today, empty strings will return a `ConfigurationError` with a descriptive message about what's missing. Once again, we appreciate the feedback and thank you for your patience!
