### ISSUE TITLE
RiskData decision should be an enum

### ISSUE THREAD

**Issue by chrylis** [braintree/braintree_java#21]
The `RiskData` class has a `decision` that is one of a few values. These values should be enum values instead of arbitrary strings.

This would be a breaking change to override the `decision` property directly, but it could be converted to an enum field with a delegating getter.

**Comment by raymondberg** [comment]
Thanks for your suggestion, @chryslis! That approach is definitely possible, but it would require a significant rework of many more components than just `RiskData`. At this time it is not practical do such a rewrite, but we will add it to consideration for future major-version bumps.
