### ISSUE TITLE
Wrong repository information in the scm section of Maven configuration

### ISSUE THREAD

**Issue by arteam** [braintree/braintree_java#22]
In [pom.xml](https://github.com/braintree/braintree_java/blob/master/pom.xml#L19-L22)
````xml
 <scm>
      <url>
        https://github.com/braintree/braintree-java.git
      </url>
</scm>
````

I believe, the correct repository URL should be https://github.com/braintree/braintree_java.git

**Comment by dewyze** [comment]
@arteam You are correct, this will be fixed in our next release. Thanks for pointing that out!

**Comment by dewyze** [comment]
Closing. This will be in the next release.
