### ISSUE TITLE
Please add currencyIsoCode to MerchantAccount 

### ISSUE THREAD

**Issue by thhalm** [braintree/braintree_java#26]
The class `MerchantAccount` does not provide access to the information of the merchant account's assigned currency (although is included in the source `NodeWrapper`  in node `currency-iso-code`). 

Would be great to have access to this information in order to implement some validation checks in the code. Thanks!

**Comment by wjr1985** [comment]
This is now available in 2.53.0 https://github.com/braintree/braintree_java/commit/35bb511711897618386a4d7256e7eece74108849

**Comment by thhalm** [comment]
Thanks a lot. Really appreciated.
