### ISSUE TITLE
Add customerId to all PaymentMethods

### ISSUE THREAD

**Issue by chancedowns** [braintree/braintree_java#28]
The ruby code has the customer_id on all PaymentMethods, but it hasn't been added to the java code.

https://github.com/braintree/braintree_ruby/commit/abc2f237e5c521ba15819f9a95555b55af2b042f

**Comment by kexline4710** [comment]
@chancedowns We are aware of this issue and will include a fix in an upcoming release, so you'll be able to get a customerId on all types of PaymentMethod methods. Thank you for the feedback!
