### ISSUE TITLE
Missing constant in Reason enum

### ISSUE THREAD

**Issue by hasnainjaved** [braintree/braintree_java#32]
The client throws the following error when fetching a transaction.

No enum constant com.braintreegateway.Dispute.Reason.UNRECOGNIZED

There is no "UNRECOGNIZED" constant defined in Reason enum.

Kind Regards

**Comment by jdlc** [comment]
You are correct, Dispute.Reason does not have an UNRECOGNIZED enum, but [Dispute.Status and Dispute.Kind do] (https://github.com/braintree/braintree_java/blob/master/src/main/java/com/braintreegateway/Dispute.java#L10-L36). Is it possible you have selected the wrong enum type? I can't provide further help without more details about your integration, and GitHub isn't the best forum for debugging integrations. I'm closing this issue and encourage you to reach out to [Braintree support](https://support.braintreepayments.com) to provide specific information about your account and integration.
