### ISSUE TITLE
Source code is not java 1.5 compliant 

### ISSUE THREAD

**Issue by jagarza** [braintree/braintree_java#34]
Some merchants with old but robust and big stacks might be using java 1.5 still in their servers. 
They would fail to import the jars or recompile the code. 
Could we provide a Java 1.5 compliance code? (current requires 1.6). Only RequestBuilder and Environment need to be slightly changed.

**Comment by crookedneighbor** [comment]
Thanks for your interest, but since Java 1.5 has been EOL by Oracle, we don't plan to make any changes to the SDK to make it compliant with Java 1.5.
