### ISSUE TITLE
HTTP 406 on find/delete customer in Sandbox

### ISSUE THREAD

**Issue by agentgt** [braintree/braintree_java#4]
I'm not sure if this is just an issue with the sandbox but periodically when our integration tests run we get this exception:
com.braintreegateway.exceptions.UnexpectedException: Unexpected HTTP_RESPONSE 406

Customer customer = gateway.customer().find("the_customer_id");

When it should be a NOT_FOUND exception.

Are any others getting this exception? Should I bring this up with braintree support?

**Comment by LokiOfNZ** [comment]
Ah, I was trying to use email addresses like 'joe.bloggs@domain.com' as the customer id ... doesn't sound like this will work?
