### ISSUE TITLE
Version 2.57.0 breaks on Google AppEngine

### ISSUE THREAD

**Issue by dincek** [braintree/braintree_java#40]
Hi,

you have added logging support, but you used restricted class "java.util.logging.ConsoleHandler" on Google AppEngine, so this library does not work, it is not possible to override or do anything to be able to use 2.57.0 on AppEngine. Version 2.56.0 still works on AppEngine.

Please add support for constructor BraintreeGateway for passing Logger instead of static initialisation with new ConsoleHandler() in Configuration.

Dean

**Comment by pblesi** [comment]
@dincek 

Thanks for bringing this to our attention. We will remove the dependency on  `java.util.logging.ConsoleHandler` and release a new version of the library. We will update this thread once the new version has been released.

**Comment by AIMMOTH** [comment]
Version 2.58.0 still breaks App Engine

java.lang.NoClassDefFoundError: java.util.logging.ConsoleHandler is a restricted class. Please see the Google  App Engine developer's guide for more details.
        at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:52)
        at com.braintreegateway.Configuration.<clinit>(Configuration.java:25)
        at com.braintreegateway.BraintreeGateway.<init>(BraintreeGateway.java:56)

**Comment by kexline4710** [comment]
@dineck @AIMMOTH
​
The fix to resolve this dependency is now released in version 2.59.0.  I will close this issue as resolved, but let us know if you continue to see issues.
