### ISSUE TITLE
PaymentMethodOptionsRequest does not contain .verificationAmount(…)

### ISSUE THREAD

**Issue by ngheungyu** [braintree/braintree_java#42]
As CreditCardRequest is deprecated, PaymentMethodRequest does not allow us to verify card with a specific amount.

However it's in the doc:
https://developers.braintreepayments.com/reference/request/payment-method/create/java#options.verification_amount

Thanks.

**Comment by pblesi** [comment]
@ngheungyu Thank you for pointing this out!

We will look to add this functionality in an upcoming release and will update you once it has been released.

**Comment by omgrr** [comment]
Hey @ngheungyu, this went out today in 2.64.0 00730a432d8bcf9a0ded2e7a357f023109f893ed. Thanks again for bringing this to our attention!

**Comment by ngheungyu** [comment]
Awesome! Appreciate it.
