### ISSUE TITLE
creditCardNumber() in search API only allows one of startsWith/endsWith

### ISSUE THREAD

**Issue by sg3391** [braintree/braintree_java#62]
When using the search endpoint, creditCardNumber(https://developers.braintreepayments.com/reference/request/transaction/search/java#credit_card_number) should ideally support both startsWith and endsWith but the correct implementation only allows filtering by one of them

**Comment by bluk** [comment]
Thanks for the suggestion. We will look into this.

**Comment by bluk** [comment]
This should be fixed in version [2.79.0](https://github.com/braintree/braintree_java/blob/master/CHANGELOG.md#2790). It will take a little bit to distribute throughout Maven but should be available in a couple hours.
