### ISSUE TITLE
Interactions with MerchantAccountGateway are hard to test because class is marked as final. 

### ISSUE THREAD

**Issue by kmichalak** [braintree/braintree_java#64]
### General information

* SDK/Library version: 2.81.1
* Environment: N/A
* Language, language version, and OS: Any version of Java and any OS

### Issue description
The class com.braintreegateway.MerchantAccountGateway has been marked as final, what makes it pretty hard to use in tests. 
As I can see it's the only gateway class that has been implemented in that way. Is there any specific reason for that? If not could you please change this, as without using additional libraries that can mock MerchantAccountGateway object through reflection it is pretty hard to write tests which include this gateway in the flow.

**Comment by crookedneighbor** [comment]
Sorry for the delay. Thanks for the report, we're looking into this. It's not the only one that uses this pattern, but the ones that do are in the minority. I'm going to review them and see if we can make this change.

**Comment by crookedneighbor** [comment]
This is fixed in 2.84.0
