### ISSUE TITLE
Can BraintreeGateway be reused and is it thread safe?

### ISSUE THREAD

**Issue by loodakrawa** [braintree/braintree_java#65]
Hi,

This is not an issue report - just a question as I couldn't find this info in the docs.

Is the BraintreeGateway designed to be reused for multiple requests and if yes, is it thread-safe?

Thanks

**Comment by crookedneighbor** [comment]
It is fine to use it for multiple requests, but try to keep it to below 25 concurrent requests. Running too many requests at once can result in rate limiting (especially in Sandbox, which has fewer resources than Production)

[Reach out to our support team if you have further questions about this.](https://articles.braintreepayments.com/forms/contact)
