### ISSUE TITLE
Maven failed to build this java package

### ISSUE THREAD

**Issue by BrianHo888** [braintree/braintree_java#67]
![2018-11-02_11-07-31](https://user-images.githubusercontent.com/31257988/47934272-26116380-de94-11e8-811d-07c1456b4f0d.jpg)
### General information

* SDK/Library version: JAVA 11
* Environment: Sandbox
* Language, language version, and OS: Java 11 on Windows 7

### Issue description
Maven failed to build this package.  Please see attachment for detail.  Based on the ReadMe, I enter "mvn package" command to build this package with no success.  Any suggestion?

Thanks,

**Comment by crookedneighbor** [comment]
> SDK/Library version: JAVA 11

What version of the Braintree SDK are you trying to download? You put the version of Java you are using instead.

**Comment by kmichalak** [comment]
@BrianHo888 The issue does not seem to be related to the library itself, but rather to the ``javac`` provided by JDK 11. If you will try to compile any class, even one that does not belong to the project using plain javac compiler with 1.5 source/target parameters set you will get error message like this 

    warning: [options] bootstrap class path not set in conjunction with -source 5        
    error: Source option 5 is no longer supported. Use 6 or later.                                                          
    error: Target option 1.5 is no longer supported. Use 1.6 or later.         

You can check it on yourself by running command 

    javac SomeClass.java -source 1.5 -target 1.5

For sure you should be able to compile the library using JDK 8.

**Comment by BrianHo888** [comment]
> > SDK/Library version: JAVA 11
> 
> What version of the Braintree SDK are you trying to download? You put the version of Java you are using instead.

I downloaded it from: https://github.com/braintree/braintree_java

**Comment by BrianHo888** [comment]
> @BrianHo888 The issue does not seem to be related to the library itself, but rather to the `javac` provided by JDK 11. If you will try to compile any class, even one that does not belong to the project using plain javac compiler with 1.5 source/target parameters set you will get error message like this
> 
> ```
> warning: [options] bootstrap class path not set in conjunction with -source 5        
> error: Source option 5 is no longer supported. Use 6 or later.                                                          
> error: Target option 1.5 is no longer supported. Use 1.6 or later.         
> ```
> You can check it on yourself by running command
> 
> ```
> javac SomeClass.java -source 1.5 -target 1.5
> ```
> For sure you should be able to compile the library using JDK 8. Also suggestion from error message to force minimum version of source/target Java version 1.6 will do the trick.



> @BrianHo888 The issue does not seem to be related to the library itself, but rather to the `javac` provided by JDK 11. If you will try to compile any class, even one that does not belong to the project using plain javac compiler with 1.5 source/target parameters set you will get error message like this
> 
> ```
> warning: [options] bootstrap class path not set in conjunction with -source 5        
> error: Source option 5 is no longer supported. Use 6 or later.                                                          
> error: Target option 1.5 is no longer supported. Use 1.6 or later.         
> ```
> You can check it on yourself by running command
> 
> ```
> javac SomeClass.java -source 1.5 -target 1.5
> ```
> For sure you should be able to compile the library using JDK 8. Also suggestion from error message to force minimum version of source/target Java version 1.6 will do the trick.

Thanks for the clarification.  It looks like I will need to fallback to JDK 8 and see if I can compile it.  Oracle will end JDK 8 support in 1/2019.  I upgraded to JDK 11 from https://www.oracle.com/technetwork/java/javase/overview/index.html

**Comment by crookedneighbor** [comment]
This should no longer be an issue as of 2.96.0
