### ISSUE TITLE
the paypal detail is not the same as the doc

### ISSUE THREAD

**Issue by wuxiongliu1** [braintree/braintree_java#69]
### General information

* SDK/Library version: 2.91.0 
* Environment: Sandbox 
* Language, language version, and OS:  Java 1.8 

### Issue description

Transaction.getPayPalDetails() did't has the propperty  `getRefundFromTransactionFeeAmount` 
 as describe in doc [https://developers.braintreepayments.com/reference/response/transaction/java#paypal_details.refund_from_transaction_fee_amount](url)

**Comment by Epreuve** [comment]
Hey @wuxiongliu1 Good catch, and thanks for the heads up.  We'll take a look at this and see if we can get this fixed up.

**Comment by wuxiongliu1** [comment]
> Hey @wuxiongliu1 Good catch, and thanks for the heads up. We'll take a look at this and see if we can get this fixed up.

thank you for you reply, Can I get the RefundFromTransactionFeeAmount from another way ?

**Comment by Epreuve** [comment]
Not currently, but we're going to get the missing method added in, and I'll post back here once we have a release with it included.

**Comment by wuxiongliu1** [comment]
ok， thanks very much . I also have a question about the Dispute fee. Can we get dispute fee from the Dispute entity ?

**Comment by wuxiongliu1** [comment]
there is a strong need for the RefundFromTransactionFeeAmount result. Because our project will move to production system. So can I have other ways to fetch this result ?

**Comment by crookedneighbor** [comment]
Please reach out to our support team for help with your integration

https://help.braintreepayments.com/

**Comment by wuxiongliu1** [comment]
I have solve the problem , But I have another question, when partial refund one transaction for many times, but the getRefundFromTransactionFeeAmount always have value , does this mean the paypal will give back the refund fee every time?

**Comment by crookedneighbor** [comment]
Your best course of action is still to reach out to our support team. https://help.braintreepayments.com
