### ISSUE TITLE
Add settledAt to Transaction Search response object

### ISSUE THREAD

**Issue by codeniko** [braintree/braintree_java#70]
### General information

* SDK/Library version: 2.91.0
* Environment: Sandbox
* Language, language version, and OS: java 1.8.0_181 on MacOS 10.14.3

### Issue description
When I search for transactions, I'm interested in the `settledAt` time. Why are `createdAt` and `updatedAt` times exposed but not `settledAt`?

Alternatively, if I do a search for transactions and one of my request conditions is `settledAt().lessThanOrEqualTo(cal)`, is it safe to assume that the result transactions I get back are ALWAYS settled and `updatedAt` time actually reflects `settledAt`? If not, please consider exposing `settledAt` time in the transaction response object.

**Comment by hollabaq86** [comment]
Hi @codeniko, to determine when a transaction was settled, check the response object's [status history](https://developers.braintreepayments.com/reference/response/transaction/java#status_history). It contains events with [details](https://developers.braintreepayments.com/reference/response/transaction/java#status-history-details) such as the timestamp a transaction received the `Settled` status.
