### ISSUE TITLE
discountAmount returns null when a discount applied to transaction in search results

### ISSUE THREAD

**Issue by codeniko** [braintree/braintree_java#71]
### General information

* SDK/Library version: 2.91.0
* Environment: Sandbox
* Language, language version, and OS: java 1.8.0_181 on MacOS 10.14.3

### Issue description
I have one subscription (initial recurring) transaction in my sandbox environment with a discount applied. When I search for all sale transactions which includes the above discounted transaction, I'm noticing an inconsistency when looking at the returned `discountAmount` value and `discounts` object. `discounts.size` tells me there is 1 discount and `discounts[0].amount` gives me the correct discount amount value, however `discountAmount` gives me null every single time.

My TransactionSearchRequest is a simple
```kotlin
TransactionSearchRequest().type().`is`(SALE)
```

**Comment by hollabaq86** [comment]
Hi @codeniko, transaction response objects will have a `discountAmount` if that value was [supplied](https://developers.braintreepayments.com/reference/request/transaction/sale/java#discount_amount) in the `transaction.sale()` request that created the transaction. 

Transaction response objects will have data in the `discounts` [object](https://developers.braintreepayments.com/reference/response/transaction/java#discounts) if the transaction was created from a subscription that had any discounts applied.

We can make our docs a little more clear about these differences, I'll forward this feedback on to our Docs team.
