### ISSUE TITLE
WebhookTestingGateway allow configurable notifications

### ISSUE THREAD

**Issue by mike-ruane** [braintree/braintree_java#73]
I'm using the WebhookTestingGateway to generate test Notifications. My programme does something depending on values of the `kind` on a `Dispute`. I want to be able to generate `Disputes` where I can give in different values. For example:

`gateway.webhookTesting().sampleNotification(WebhookNotification.Kind.DISPUTE_OPENED, "my_id")` could maybe take other parameters that would set values in the xml appropriately.

Thanks

**Comment by hollabaq86** [comment]
Hi @mike-ruane, thanks for reaching out. Can you elaborate on your use case? What additional attributes of the dispute webhooks would you want to be able to specify in the `sampleNotification` request?

**Comment by mike-ruane** [comment]
Yes sure, sorry it was a bit thin on detail.

So, my use case is I want to filter out a particular `Dispute` kind - namely `RETRIEVAL`. So I want to mock up a notification that has `Dispute.getKind` as `RETRIEVAL`. At current, for a `DISPUTE_OPENED`mock notification, the [kind of dispute is hard coded](https://github.com/braintree/braintree_java/blob/master/src/main/java/com/braintreegateway/WebhookTestingGateway.java#L262). I'd want to be able to set this value to retrieval. 

I hope that's clearer.

**Comment by crookedneighbor** [comment]
We're brainstorming some solutions. 

In the meantime, since the sample notification is a simple hash map, you should be able to get the value of the payload, base64decode it, do a string replacement of `chargeback` with `retrieval`, then base64 encode it again, and replace the old payload with the new payload.

(yes, this is extremely hacky, but it should get you unstuck)

**Comment by hollabaq86** [comment]
Closing this issue, as we've forwarded this feature request on to another team for investigation.
