### ISSUE TITLE
Valid card numbers available for test are declined with little descriptive error message

### ISSUE THREAD

**Issue by maguilar98** [braintree/braintree_java#76]
### General information

We are using Braintree as the Payment Gateway from Zuora sandbox.
From Zuora [docs](https://knowledgecenter.zuora.com/CB_Billing/M_Payment_Gateways/Supported_Payment_Gateways/Braintree_Gateway): The Braintree payment gateway uses version 2.81.0 of the Braintree Java JAR.

### Issue description

Valid card numbers available for test from this [page](https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/node) are declined with the following error message:
```
[GatewayTransactionError]  Transaction declined.Approved - Approved
```
What does it mean?

The error started popping up recently. 
We didn't have this problem before so we are not sure what's going on.

**Comment by crookedneighbor** [comment]
Please reach out to support so they can help you troubleshoot your integration https://help.braintreepayments.com/
