### ISSUE TITLE
CreditCardVerification does not contain method `paymentMethodToken`

### ISSUE THREAD

**Issue by taijuten** [braintree/braintree_java#79]
### General information

* SDK/Library version: 2.105
* Environment: All
* Language, language version, and OS: Java 8

### Issue description

As briefly described in the title, the method documented here: https://developers.braintreepayments.com/reference/request/credit-card-verification/search/java#payment-methods
Does not exist in the Java SDK.

I've looked in the source to verify this.

**Comment by Epreuve** [comment]
Hey @taijuten Thanks for letting us know about this!  We'll take a look at getting this fixed up.

**Comment by crookedneighbor** [comment]
This is out in v2.109.0
