### ISSUE TITLE
implement Serializable on API Response objects

### ISSUE THREAD

**Issue by Stexxen** [braintree/braintree_java#80]
### General information

This is a request for change.

### Issue description

Can the Response objects from the API implement the java.io.Serializable interface.
an Example would be com.braintreegateway.Customer

We use caching via Redis, and integration via a JMS Queue, and not having to convert the data into JSON string and then convert back when inflating would be very useful.

Would you expect a PR for this?

**Comment by crookedneighbor** [comment]
As long as this doesn't add a new dependency to the SDK, and doesn't break backwards compatibility, we'd be happy to review a PR.

**Comment by crookedneighbor** [comment]
We're going to close this due to inactivity. Feel free to open a PR for this in the future and we're happy to review it.
