### ISSUE TITLE
Method Transaction.getRetrievalReferenceNumber() is not available in latest Java SDK

### ISSUE THREAD

**Issue by jmsjr** [braintree/braintree_java#82]
### General information

* SDK/Library version: 2.106.0
* Environment: Sandbox 
* Language, language version, and OS: OpenJDK8 on RHEL7

### Issue description

According to this:

https://developers.braintreepayments.com/reference/response/transaction/java#retrieval_reference_number

The getRetrievalReferenceNumber() should exist but the latest version 2.106.0 does not have this.

**Comment by sestevens** [comment]
@jmsjr Thanks for raising this issue! You're right, this field doesn't seem to be exposed in the Java SDK. We will look into this and post here once with any updates.

**Comment by hollabaq86** [comment]
👋 @jmsjr, this was added to [2.107.0](https://github.com/braintree/braintree_java/blob/master/CHANGELOG.md#21070).

I'm going to go ahead and close this issue, but feel free to create a new issue if there are any issues with the getRetrievalReferenceNumber.
