### ISSUE TITLE
Last delivery unsuccessful. Invalid server response 

### ISSUE THREAD

**Issue by Mycheers** [braintree/braintree_java#95]
### General information

* SDK/Library version: 3.3.0
* Environment: Sandbox
* Language, language version, and OS: Java 1.8.0

### Issue description
Click on “Check URL”
Last delivery unsuccessful. Invalid server response 

Use https protocol

**Comment by hollabaq86** [comment]
👋 @Mycheers please [contact Support](https://help.braintreepayments.com/) with more information on what you're trying to integrate when you get this response, they can assist in troubleshooting.

**Comment by lifeiteng** [comment]
@Mycheers Did you fixed it?
