### ISSUE TITLE
How to refund a transaction with status "submitted for settlement".

### ISSUE THREAD

**Issue by chenxing-luckysky** [braintree/braintree_java#98]
### General information

* SDK/Library version: the lastest
* Environment: sandbox
* Language, language version, and OS: java8

### Issue description
after a customer make an order, and he refund it partially and immediately. how can I refund a transaction with status "submitted for settlement". refund only works for transactions that with status"settled"and "settling". I try to clone a transaction and void the old one, it give error that Transaction cannot be cloned if payment method stored in vault. 
Can anyone give me an idea that how to refund it?

**Comment by sestevens** [comment]
Hi @chenxing-luckysky, in this case you'll need to [void](https://developers.braintreepayments.com/reference/request/transaction/void/java) the transaction rather that refund it. You may want to take a look at our support article on [refunds and voids](https://articles.braintreepayments.com/control-panel/transactions/refunds-voids-credits).
